name: simple_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.0
  custom_lint: ^0.5.11

flutter:
  uses-material-design: true
