name: simple_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.1
  sqlite3_flutter_libs: ^0.5.39
  flutter_riverpod: ^3.0.0-dev.17
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0
  riverpod_lint: ^3.0.0-dev.17
  riverpod_generator: ^3.0.0-dev.17

flutter:
  uses-material-design: true